### ISSUE TITLE
[FE] 사파리 대응

### ISSUE THREAD

**Issue by hae-on** [woowacourse-teams/2023-fun-eat#303]
## 버그가 발생한 곳

현재 사파리에 다이얼로그가 열리지 않는 버그가 있습니다.

## 버그 상황 재연

스크린샷을 첨부하면 더 좋아요!

- 어떤 행동을 했을 때 버그가 발생하는지 작성합니다.

## 현재 동작

- 버그가 발생하는 동작에 대해 작성합니다.

## 기대 동작

- 원래 기대하던 정상 동작에 대해 작성합니다.

**Comment by xodms0309** [comment]
시도 1. dialog 태그에 z-index 속성을 추가한다. https://github.com/fun-eat/design-system/pull/58

**Comment by xodms0309** [comment]
시도2. 이 방법으로 해결. height: fit-content 삭제 https://github.com/fun-eat/design-system/issues/59
