### ISSUE TITLE
[BE] 음식 아이템 리뷰에서 하트를 계속 누르면 마이너스가 됩니다!

### ISSUE THREAD

**Issue by ukkodeveloper** [woowacourse-teams/2023-fun-eat#329]
## 버그가 발생한 곳
음식 아이템 리뷰 화면에서 좋아요(하트)를 계속 누르다면 마이너스가 됩니다!

## 버그 상황 재연
<img width="713" alt="image" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/109048739/0fc2cd2c-5024-4f22-a530-5626d41393b7">

## 기대 동작

계속 눌러도 하트 수가 제대로 작성되었으면 좋겠어요

**Comment by Go-Jaecheol** [comment]
버그 발생했을 때 어느 브라우저 사용했는지 알 수 있을까요??

**Comment by somsom13** [comment]
브라우저 상관없이 발생하는 것 같습니다!
현재까지 확인된 브라우저: 크롬, 사파리
