### ISSUE TITLE
[ALL] 좋아요를 계속 누르면 좋아요 수가 이상해져요 

### ISSUE THREAD

**Issue by splitCoding** [woowacourse-teams/2023-fun-eat#330]
## 버그가 발생한 곳

<img width="575" alt="image" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/75476562/4f443373-7dad-4d94-b6de-02d3327b1346">

## 버그 상황 재연

좋아요를 미친듯이 연타했습니다.

## 현재 동작

미친듯이 연타할 경우 숫자가 막올라가기도 내려가기도 합니다.

## 기대 동작

계속 눌러도 좋아요가 제대로 반영되어야 합니다.

**Comment by xodms0309** [comment]
https://github.com/woowacourse-teams/2023-fun-eat/issues/329
중복 이슈입니다!
