### ISSUE TITLE
[FE] 상품 전체보기 페이지 뒤로가기 바로 안되는 문제

### ISSUE THREAD

**Issue by kangyeongmin** [woowacourse-teams/2023-fun-eat#331]
## 버그가 발생한 곳

<img width="645" alt="스크린샷 2023-08-07 오후 1 51 03" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/62367797/d21065b4-b763-40ed-b336-c0416d2bb6ed">

- 버그가 발생한 페이지나 기능을 작성합니다.

## 버그 상황 재연

스크린샷을 첨부하면 더 좋아요!

- 어떤 행동을 했을 때 버그가 발생하는지 작성합니다.
: 공통상품과 PB상품을 토글할때마다, 스택이 쌓여서 뒤로가기가 이전 홈페이지로 되지 않는 것 같습니다.

## 현재 동작

- 버그가 발생하는 동작에 대해 작성합니다.
토글동작의 횟수만큼 뒤로가기가 되지 않아요!

## 기대 동작

- 원래 기대하던 정상 동작에 대해 작성합니다.

뒤로가기를 누르면 바로 홈 페이지로 가야할 것 같아요!

**Comment by eunkeeee** [comment]
공통상품, PB 상품이 아래 토글이 있으면 두 가지더라도 목록이 뜨면 더 자연스러울 것 같아요 그냥 변하는게 약간 어색하게 느껴집니다
