### ISSUE TITLE
[FE/BE] 리뷰 등록 시에 이모지를 넣으면 500 에러가 발생해요

### ISSUE THREAD

**Issue by ukkodeveloper** [woowacourse-teams/2023-fun-eat#332]
## 버그가 발생한 곳

리뷰 등록 시에 이모지를 넣으면 500 에러가 발생해요
## 버그 상황 재연
![Aug-07-2023 13-53-00](https://github.com/woowacourse-teams/2023-fun-eat/assets/109048739/a8559f21-35c3-4f30-b219-cfc6ad54834d)

## 현재 동작
이모지를 넣으면 에러가 발생하는 것 같아요!

## 기대 동작
이모지도 작성하게 해주세요!  이모지 작성이 안되는 정책이라면, 모달로 알려주시면 좋을 것 같습니다 ! 펀잇 화이팅!

**Comment by wugawuga** [comment]
<img width="297" alt="image" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/91244090/c391b340-200b-4ea2-ad73-f112784ce1a4">

해결했습니다 ㅎㅎ
