### ISSUE TITLE
[FE] 목록 탭에서 PB상품, 고객상품을 번갈아서 누르면 데이터가 안맞는 경우가 있어요

### ISSUE THREAD

**Issue by youngh0** [woowacourse-teams/2023-fun-eat#334]
## 버그가 발생한 곳

- 목록 페이지

## 버그 상황 재연

- 목록 페이지에서 고객상품, PB상품 부분을 여러번 눌렀더니 PB상품인데 고객상품 데이터가 나와요

<img width="1440" alt="스크린샷 2023-08-07 오후 1 53 21" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/62167801/507bf820-700d-4eb4-ab04-be6a03850f6a">

## 현재 동작

- 뭔가 우연의 일치로 나온 버그 같아요

## 기대 동작

- 여러 번 눌러도 현재 탭에 맞는 데이터가 나올 줄 알았는데 다른 데이터가 나왔습니다!

**Comment by xodms0309** [comment]
버그 재발생시 다시 이슈 열겠습니다.
