### ISSUE TITLE
[FE] 홈 > 랭킹에서 치킨마요삼각김밥을 눌러도 해당 제품으로 안들어가져요

### ISSUE THREAD

**Issue by eunkeeee** [woowacourse-teams/2023-fun-eat#335]
## 버그가 발생한 곳

- 버그가 발생한 페이지나 기능을 작성합니다.
![image](https://github.com/woowacourse-teams/2023-fun-eat/assets/107979804/97dab881-9a54-49bb-bfb4-2e76b9b5f84c)

## 버그 상황 재연

스크린샷을 첨부하면 더 좋아요!

- 어떤 행동을 했을 때 버그가 발생하는지 작성합니다.

## 현재 동작

- 아무 일도 안 일어남

## 기대 동작

- 리뷰로 들어가지면 좋을 것 같아요

**Comment by xodms0309** [comment]
아직 구현 안 된 사항입니다!

**Comment by xodms0309** [comment]
TODO
상품 랭킹 api에 카테고리를 받아서 라우팅 시키기
