### ISSUE TITLE
[FE] 사파리 브라우저에서 목록 버튼을 누르면 정렬 방법 고르는 창이 뜨고 그 창이 없어지지가 않습니다

### ISSUE THREAD

**Issue by yenawee** [woowacourse-teams/2023-fun-eat#337]
## 버그가 발생한 곳

- 사파리 브라우저 (목록 탭)

## 버그 상황 재연

스크린샷을 첨부하면 더 좋아요!

<img width="500" alt="스크린샷 2023-08-07 오후 2 05 35" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/91937954/5722482b-8211-4d9a-b9c2-28742c8a031f">

- 어떤 행동을 했을 때 버그가 발생하는지 작성합니다.

## 현재 동작

- 사파리 브라우저에서 목록 버튼을 누르면 정렬 방법 고르는 창이 뜨고 그 창이 없어지지가 않습니다! 

## 기대 동작

- 상품 목록이 뜨기를 기대했습니다 !

**Comment by xodms0309** [comment]
사파리 버전 15.3까지는 dialog 태그를 지원하지 않는 오류입니다.
https://caniuse.com/?search=dialog
(cc @hae-on @Leejin-Yang )
