### ISSUE TITLE
[ALL] < 버튼의 동작이 생각과 좀 다르네요😊

### ISSUE THREAD

**Issue by splitCoding** [woowacourse-teams/2023-fun-eat#339]
## 버그가 발생한 곳

<img width="623" alt="image" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/75476562/c1f33ac3-44d8-47e5-915e-bfdae56e452d">

## 버그 상황 재연

< 를 누르면 목록이 아닌 이전페이지로 이동하더라구요!

## 현재 동작

< 를 누르면 목록이 아닌 이전페이지로 이동

## 기대 동작

< 누르면 제품 상세 페이지에서 목록으로 이동

**Comment by wugawuga** [comment]
@splitCoding 사용자의 편의성을 위해 실제 사용자의 이전 페이지로 돌아가도록 의도된 것 입니다!!
