### ISSUE TITLE
[ALL] 좋아요를 연타하면 일시적으로 필요이상의 숫자가 올라가거나 내려가는 현상

### ISSUE THREAD

**Issue by 2yunseong** [woowacourse-teams/2023-fun-eat#340]
## 버그가 발생한 곳
- 버그가 발생한 페이지나 기능을 작성합니다.
<img width="718" alt="Screenshot 2023-08-07 at 14 28 48" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/56749516/f4e9fc3b-abe0-4792-afff-1f07128e0197">

## 버그 상황 재연
- 좋아요 버튼을 연타

## 현재 동작
- 페이지를 새로고침 하기 전까지 임의의숫자가 발생

## 기대 동작

- 자신의 좋아요에만 숫자가 반영

**Comment by xodms0309** [comment]
https://github.com/woowacourse-teams/2023-fun-eat/issues/329
중복 이슈입니다!

**Comment by 2yunseong** [comment]
앗 클로즈 하겠습니다!!
