### ISSUE TITLE
[FE] 리뷰 글자수 제한 버그

### ISSUE THREAD

**Issue by kangyeongmin** [woowacourse-teams/2023-fun-eat#341]
## 버그가 발생한 곳

- 버그가 발생한 페이지나 기능을 작성합니다.
<img width="661" alt="스크린샷 2023-08-07 오후 2 32 26" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/62367797/e6c1f967-0050-4fe2-a098-ab59072c29aa">

리뷰 작성하는 곳

## 버그 상황 재연

스크린샷을 첨부하면 더 좋아요!

- 어떤 행동을 했을 때 버그가 발생하는지 작성합니다.

글자수가 201자까지 입력되는거 같아요.

## 현재 동작

- 버그가 발생하는 동작에 대해 작성합니다.

## 기대 동작

- 원래 기대하던 정상 동작에 대해 작성합니다.

200자가 넘지 않으면 좋겠어요

**Comment by Leejin-Yang** [comment]
해결해서 이슈 닫습니다.!
