### ISSUE TITLE
[FE] storybook 배포 자동화

### ISSUE THREAD

**Issue by xodms0309** [woowacourse-teams/2023-fun-eat#45]
## 어떤 기능을 구현하나요?

> 프론트엔드 리소스 빌드 및 배포 환경 구축 (AWS)
> 테스트 전략 수립 및 테스트 자동화

- 2차 데모데이 요구사항이 위와 같기도 하고 스토리북 배포가 안되어 캡처로 확인하려니 너무 힘들어서 이번 스프린트에 진행 필요

**Comment by Leejin-Yang** [comment]
캠퍼스에서 서로 확인 가능해서 스토리북 불필요하다 판단. 이슈 닫겠습니다.!
