### ISSUE TITLE
[ALL] 닉네임 길이가 몇 자까지 되는지 사용자에게 알려 준다

### ISSUE THREAD

**Issue by pinkishincoloragain** [woowacourse-teams/2023-fun-eat#580]
## 버그가 발생한 곳

- 닉네임을 500자로 하려고 했더니 오류가 발생했어요 :/

## 버그 상황 재연

닉네임을 500자로 설정하려고 하면 오류가 발생해요
레이아웃도 조금 이상해져요.

<img width="617" alt="Screenshot 2023-09-08 at 2 49 59" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/39547381/47fefb51-5044-4ff9-82c4-3cc6c9c0ddfd">

## 현재 동작

<img width="635" alt="Screenshot 2023-09-08 at 2 50 37" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/39547381/44ccbf66-7f90-4e49-9baf-d5d8775a6d27">

- 알 수 없는 에러입니다. 가 발생해요

## 기대 동작

- 닉네임 길이는 몇 자까지 되는지 알려 주면 좋겠어요!

## 펀잇팀 화이팅!

- 앱이 너무 멋져요. 화이팅.
![DBDC](https://github.com/woowacourse-teams/2023-fun-eat/assets/39547381/435f0780-b631-42aa-bd06-a1e1931e571e)

**Comment by Leejin-Yang** [comment]
#625
