### ISSUE TITLE
[FE] CI/CD 구축

### ISSUE THREAD

**Issue by xodms0309** [woowacourse-teams/2023-fun-eat#61]
## 어떤 기능을 구현하나요?

- CI/CD 구축

## 일정

- 8시간

**Comment by Leejin-Yang** [comment]
![스크린샷 2023-07-19 오후 2 35 19](https://github.com/woowacourse-teams/2023-fun-eat/assets/78616893/436b24c9-8173-4c7b-930e-653bfb3745f0)

젠킨스 스크립트 작성 완료, 빌드

![스크린샷 2023-07-19 오후 2 36 29](https://github.com/woowacourse-teams/2023-fun-eat/assets/78616893/81561e73-20be-4464-b22e-547dc1ee3327)
 완료
