### ISSUE TITLE
[BE] 젠킨스 슬랙 연동

### ISSUE THREAD

**Issue by Go-Jaecheol** [woowacourse-teams/2023-fun-eat#76]
## 어떤 기능을 구현하나요?

- 젠킨스 CI/CD 과정을 슬랙을 통해 알 수 있도록 연동한다.

## 일정

- 추정 시간 : 30min

**Comment by hanueleee** [comment]
<img width="1251" alt="image" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/91522259/9c899379-5218-4595-b3de-027e65719759">

실제 시간 : 30m
